### PR TITLE
fix #1, better use of rc file

### LINKED ISSUE #1: N64?
When should we expect your N64 development dotfiles for MIPS?

### PR DESCRIPTION
**Pull request by wenkesj**
This should replace the need for the N64 MIPS support.

Example use case

1. Open a new terminal
screen shot 2017-04-28 at 5 59 16 pm

### CODE REVIEW

**Comment by wenkesj** [comment]
Very simple test case:
```sh
$ sed '/\_\|\_\|/!d' ~/.zshrc
```
And the output should look like this
```sh
   _|_|_|     _|_|     _|_|_|_|_|   _|_|_|_|   _|_|_|_|   _|      _|
 _|         _|    _|       _|       _|         _|         _|_|  _|_|
 _|  _|_|   _|    _|       _|       _|_|_|     _|_|_|     _|  _|  _|
   _|_|_|     _|_|         _|       _|_|_|_|   _|_|_|_|   _|      _|
```

**Comment by wenkesj** [comment]
...goteem

**Comment by austinkelleher** [comment]
If you make this a function, I will merge this lol.

**Comment by wenkesj** [comment]
Updated use case,

`$ goteem`

**Comment by austinkelleher** [comment]
Thanks. I'll put this to good use.

**Comment by austinkelleher** [comment]
screenshot from 2017-04-28 18-23-10

**Comment by wenkesj** [comment]
I just died

**Comment by charlieduong94** [comment]
I feel like the goteem text should show up every time you open a new terminal like what @wenkesj's original commit would have done. It's a good way to show that you are alpha af to anyone trying to use your setup. You should probably invoke the function right after it's definition.

**Pull request merged**
